### ISSUE TITLE
Can't find kubeconfig

### ISSUE THREAD

**Issue by abagshaw** [GoogleCloudPlatform/k8s-node-termination-handler#2]
Thanks very much for your work on this! One problem when I tried to get it going: the `node-termination-handler` container starts up and produces the following error in the logs:

```
F0618 16:10:47.732227 23581 main.go:59] Failed to get kubernetes API Server Client. Error: stat /var/lib/kubelet/kubeconfig: no such file or directory
```

Any ideas?

**Comment by mindprince** [comment]
@vishh Is this fixed now?

**Comment by vishh** [comment]
@abagshaw this should be fixed now. Can you give it a try again?

**Comment by abagshaw** [comment]
It's working - thanks very much!
