### ISSUE TITLE
Error thrown on GKE private clusterr

### ISSUE THREAD

**Issue by eric-aops** [GoogleCloudPlatform/k8s-node-termination-handler#24]
Hi, 

I've got your project running nicely on a public cluster but now I had to create a private one. The setup fo the cluster, excluding the part that makes it private, and the deployment are exactly the same as on the public one yet the node-termination-handler throws this error:

```
I0227 04:54:26.860229  772575 main.go:72] Excluding pods map[node-termination-handler-bd2d4:kube-system]
F0227 04:54:26.861467  772575 main.go:79] metadata: GCE metadata "instance/scheduling/on-host-maintenance" not defined
```

Any idea what I'm missing here? 

Kind regards, 

Eric

**Comment by tobad357** [comment]
We are seeing the same issue with a private GKE cluster.
Not quite sure why this would be different

**Comment by bobbypage** [comment]
Closing since #23 has been merged which should fix this issue.
