### ISSUE TITLE
[Question]: What about drain node, rather than deleting the pods?

### ISSUE THREAD

**Issue by rahulchheda** [GoogleCloudPlatform/k8s-node-termination-handler#31]
Might be a noob question, but just wanted to ask the reason not ti just Drain the node, rather than taking the responsibility of eviction, deletion, tainting. Can't we just cordon, and then drain the node?

**Comment by seeruk** [comment]
See the discussion in https://github.com/GoogleCloudPlatform/k8s-node-termination-handler/issues/16

TL;DR: No guarantee and eviction will complete in time. With this approach the termination can be controlled in a more specific way.
